INSERT INTO USERS (EMAIL, NAME, PASSWORD) VALUES ('eduardo@example.com', 'Eduardo', '$2a$10$PCgte6Qn5CD.7qAoz1n0gO/c21nYbF/XS.VPczYVfIzpFHD2gzyw6');

'$2a$10$PCgte6Qn5CD.7qAoz1n0gO/c21nYbF/XS.VPczYVfIzpFHD2gzyw6'	-- Contrase;a cifrada para 12345
--Ejemplo de token
eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlZHVhcmRvQGV4YW1wbGUuY29tIiwiaWF0IjoxNzc1MzUwNjcwLCJleHAiOjE3NzUzNTQyNzB9.BpldW1uSrKgVOCAKB0DVoxqCpFTCONPxTWqPgK67rcA

SELECT * FROM USERS;



CREATE TABLE PROFESSIONS (
	PROF_ID SERIAL PRIMARY KEY,
	NAME VARCHAR(50),
	DESCRIPTION VARCHAR(150)
);

CREATE TABLE USERS (
	USER_ID SERIAL PRIMARY KEY,
	EMAIL VARCHAR(255) NOT NULL UNIQUE,
	NAME VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE PROFESSIONS_USERS (
	PROF_USR_ID SERIAL PRIMARY KEY,
	PROF_ID INT REFERENCES PROFESSIONS (PROF_ID),
	USER_ID INT REFERENCES USERS (USER_ID)
)

-- si professions id es null, entonces NO es profesionista, es contratista, esto es para autenticar a USuarios en general, no por serparados xd
-- no se si hubiera sido posible con spring boot tener dos tipos de usuarios (dos tablas separadas pue)

CREATE TABLE JOB_TYPE (
	JOB_TYPE_ID SERIAL PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	DESCRIPTION VARCHAR(150) NOT NULL
);

CREATE TABLE QUESTIONS (
	QUESTION_ID SERIAL PRIMARY KEY,
	TEXT VARCHAR(150) NOT NULL,
	DATA_TYPE VARCHAR(10) NOT NULL
);

CREATE TABLE JOBS (
	JOB_ID SERIAL PRIMARY KEY,
	CONTRACTOR_ID INT,
	WORKER_ID INT,
	JOB_TYPE_ID INT NOT NULL,
	STATUS VARCHAR(25) NOT NULL,
	NAME VARCHAR(100),
	DESCRIPTION VARCHAR(255),
	COST DECIMAL,
	COST_TYPE VARCHAR(5),
	FOREIGN KEY (CONTRACTOR_ID) REFERENCES users (user_id ),
	FOREIGN KEY (WORKER_ID) REFERENCES users (user_id),
	FOREIGN KEY (JOB_TYPE_ID) REFERENCES job_type (JOB_TYPE_ID),
	CONSTRAINT JOBS_STATUS_CK CHECK (STATUS IN ('PENDING', 'SOLVED', 'CANCELED', 'WORK_NOT_ASSIGNED', 'CONT_NOT_ASSIGNED')),
	CONSTRAINT JOBS_COSTTYPE_CK CHECK (COST_TYPE IN ('/HOUR', 'TOTAL'))
);

CREATE TABLE DETAILS (
	DETAILS_ID SERIAL PRIMARY KEY,
	JOB_ID INT NOT NULL,
	QUESTION_ID INT NOT NULL,
	VALUE VARCHAR(100) NOT NULL,
	FOREIGN KEY (JOB_ID) REFERENCES JOBS (JOB_ID),
	FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONS (QUESTION_ID)
);

/*
DROP TABLE details CASCADE;
DROP TABLE job_type CASCADE ;
DROP TABLE jobs CASCADE;
DROP TABLE professions CASCADE;
DROP TABLE questions CASCADE;
DROP TABLE workers CASCADE;
DROP TABLE USERS CASCADE;
*/




