spring.application.name=chambi

spring.datasource.url=jdbc:postgresql://localhost:5432/chambitas
spring.datasource.username=chambitas_user
spring.datasource.password=INNOVATEC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect